stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_IMAGE: "mcr.microsoft.com/dotnet/sdk:9.0"

default:
  image: $DOTNET_IMAGE

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/

test:
  stage: test
  script:
    - dotnet restore
    - dotnet build
    - dotnet test --collect:"XPlat Code Coverage"
    - dotnet tool install --global dotnet-reportgenerator-globaltool
    - export PATH="$PATH:/root/.dotnet/tools"
    - reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:cobertura
    - echo "Code Coverage:"
    - grep -oP '(?<=line-rate=")[0-9.]+(?=")' ./coveragereport/Cobertura.xml
  coverage: '/<coverage line="[^"]*" branch="[^"]*" methods="[^"]*" classes="[^"]*" lines-covered="[^"]*" lines-valid="(\d+)" line-rate="(\d\.\d+)"/'
  artifacts:
    reports:
      junit: ./**/coverage.cobertura.xml
    paths:
      - coveragereport
