stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_IMAGE: "mcr.microsoft.com/dotnet/sdk:9.0"

default:
  image: $DOTNET_IMAGE

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/

test:
  stage: test
  script:
    - dotnet add package coverlet.msbuild
    - dotnet restore
    - dotnet build
    - dotnet test --collect:"XPlat Code Coverage"
  artifacts:
    reports:
      cobertura: TestResults/*/coverage.cobertura.xml
